version: '3.8'
services:
  backend-server:
    build: .
    ports:
      - "3000:3000"
    # This loads your local .env file into the container
    env_file:
      - .env
    # Restart automatically if it crashes
    restart: always